[versions]

java = "17"

# plugins
# https://github.com/researchgate/gradle-release/releases
release = "3.1.0"

# main
# https://github.com/jayo-projects/jayo-async-stream/tags
jayoAsyncStream = "0.1.0-alpha2"
# https://github.com/jspecify/jspecify/releases
jspecify = "1.0.0"

# tests
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.27.7"
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junit = "6.0.2"
# https://mvnrepository.com/artifact/org.mockito/mockito-core
mockito = "5.21.0"

[plugins]
release = { id = "net.researchgate.release", version.ref = "release" }
